/**
 * Concept dependency DAG (ADR-0002) for the Second Brain curriculum — the source
 * of truth. Hand-expanded (2026-06-21) from a thin 11-concept chain to a richer,
 * non-linear graph to surface what authoring machinery is needed (see
 * docs/MACHINERY_NEEDED.md). Every prerequisite has a PREREQ_WHY + PREREQ_KIND.
 *
 * Stage order (introducedIn) is load-bearing: a prerequisite must be introduced
 * in the same or an EARLIER stage. Cross-branch edges (e.g. entity-resolution →
 * similarity) forced the stage banding below — a manual ordering pain (R8).
 *   sb-kg(1) → sb-onto(2) → sb-reasoning(3) → sb-neural(4) → sb-neurosymbolic(5)
 */
import type { Concept, ConceptGraph } from "../types";

const CONCEPTS: Concept[] = [
  // ============ sb-kg: knowledge graphs ============
  { id: "entity", term: "entity", layer: "data", primitive: true,
    short: "A thing your second brain knows about — a person, place, idea, paper, or note. The 'nouns'.",
    example: "`Ada_Lovelace`, `category_theory`, `note_2026`.",
    prerequisites: [], contrasts: ["class", "literal"], introducedIn: "sb-kg",
    microQuiz: [{ id: "mq-entity", type: "true-false", prompt: "True or false: an entity is a specific *thing*, not a category of things.", correct: true, explanation: "An entity is one individual; its category is a class." }] },
  { id: "relation", term: "relation", layer: "data",
    short: "A named, directed link from one @c{entity} to another — the 'verbs'.",
    example: "`wrote`, `cites`, `is_about`.",
    prerequisites: ["entity"], introducedIn: "sb-kg" },
  { id: "iri", term: "IRI", layer: "system",
    short: "A global name (the Unicode-capable generalization of a URI) for an @c{entity} or @c{relation}, so the same thing means the same thing across datasets.",
    example: "`http://ex.org/Ada` rather than a bare `Ada`.",
    prerequisites: ["entity", "relation"], introducedIn: "sb-kg" },
  { id: "triple", term: "triple", layer: "data",
    short: "The atom of a knowledge graph: a subject, a predicate (@c{relation}), and an object @c{entity}.",
    example: "`(Ada, wrote, note_1)`.",
    prerequisites: ["entity", "relation"], contrasts: ["embedding", "n-ary-relation"], introducedIn: "sb-kg",
    microQuiz: [{ id: "mq-triple", type: "multiple-choice", prompt: "Which is a well-formed triple?", options: ["`Ada`", "`(Ada, wrote, note_1)`", "`wrote`", "`Ada wrote`"], correct: 1, explanation: "Subject–predicate–object." }] },
  { id: "literal", term: "literal", layer: "data", band: "foundations",
    short: "A data *value* at the object end of a @c{triple} — a date, number, or string — rather than another @c{entity}.",
    example: "`(note_1, created, \"2026-06-21\")` — the object is a literal, not an entity.",
    prerequisites: ["triple"], contrasts: ["entity"], introducedIn: "sb-kg" },
  { id: "knowledge-graph", term: "knowledge graph", layer: "data",
    short: "A set of @c{triple}s — your facts as a graph. The data layer; it holds *what is connected*, not what it means.",
    example: "All your notes + their references as one graph.",
    prerequisites: ["triple"], contrasts: ["ontology"], introducedIn: "sb-kg",
    microQuiz: [{ id: "mq-kg", type: "true-false", prompt: "True or false: a knowledge graph is data; the meaning/rules live in a separate ontology.", correct: true, explanation: "KG = data; ontology = schema + axioms." }] },
  { id: "property-graph", term: "property graph", layer: "system",
    short: "A @c{knowledge-graph} model (Neo4j) with key/value properties on nodes & edges — fast, flexible, but no built-in logical *inference* (no reasoner/entailment the way RDF+OWL has).",
    example: "Cypher: `(:Person {name:'Ada'})-[:WROTE]->(:Note)`.",
    prerequisites: ["knowledge-graph"], contrasts: ["rdf-graph"], introducedIn: "sb-kg" },
  { id: "rdf-graph", term: "RDF graph", layer: "system",
    short: "A @c{knowledge-graph} model built from @c{triple}s of @c{iri}s — the data layer that RDFS/OWL semantics and reasoning are defined *over* (RDF itself adds only thin semantics).",
    example: "Turtle: `:Ada :wrote :note_1 .`",
    prerequisites: ["knowledge-graph", "triple", "iri"], contrasts: ["property-graph"], introducedIn: "sb-kg" },
  { id: "query", term: "query", layer: "system", band: "foundations",
    short: "Asking your @c{knowledge-graph} a question — retrieving the @c{triple}s or @c{entity}s that match a pattern, instead of reading the whole graph. (The point of a *queryable* second brain.)",
    example: "\"Which notes did Ada write?\" → match `(Ada, wrote, ?note)`.",
    prerequisites: ["knowledge-graph"], introducedIn: "sb-query" },
  { id: "basic-graph-pattern", term: "basic graph pattern", layer: "system", band: "foundations",
    short: "The core of graph @c{query}: a set of @c{triple} patterns with variables that matches subgraphs of your @c{knowledge-graph}.",
    example: "`(?x, wrote, ?note) (?note, is_about, category_theory)` — who wrote a note about CT.",
    prerequisites: ["query", "triple"], introducedIn: "sb-query" },
  { id: "sparql", term: "SPARQL", layer: "system", band: "foundations",
    short: "The W3C @c{query} language for @c{rdf-graph}s — @c{basic-graph-pattern}s plus filters, joins, optional, union, and aggregation.",
    example: "`SELECT ?note WHERE { :Ada :wrote ?note }`.",
    prerequisites: ["rdf-graph", "basic-graph-pattern"], contrasts: ["cypher"], introducedIn: "sb-query" },
  { id: "cypher", term: "Cypher", layer: "system", band: "practitioner",
    short: "The @c{property-graph} @c{query} language (Neo4j) — ASCII-art patterns over nodes and edges.",
    example: "`MATCH (a:Person {name:'Ada'})-[:WROTE]->(n:Note) RETURN n`.",
    prerequisites: ["property-graph", "query"], contrasts: ["sparql"], introducedIn: "sb-query" },
  { id: "property-path", term: "property path", layer: "system", band: "practitioner",
    short: "A @c{query} over a path rather than a single hop — follow a @c{relation} repeatedly with `*`/`+` for unbounded length (SPARQL property paths, Cypher variable-length).",
    example: "`:Ada (:knows)+ ?person` — everyone reachable from Ada via knows.",
    prerequisites: ["basic-graph-pattern"], introducedIn: "sb-query" },
  { id: "n-ary-relation", term: "n-ary relation", layer: "data", band: "practitioner",
    short: "A fact relating *more than two* things — a binary @c{triple} can't hold it directly, so you introduce an intermediate @c{entity} (an event/role node).",
    example: "\"Ada gave note_1 to Bob in 1843\" → an event entity linked to giver, gift, recipient, year.",
    prerequisites: ["triple", "entity"], contrasts: ["triple"], introducedIn: "sb-modeling" },
  { id: "reification", term: "reification", layer: "data", band: "practitioner",
    short: "Turning a @c{triple} into an @c{entity} you can describe — so you can attach source, time, or confidence to the *statement itself*.",
    example: "make `(Ada, wrote, note_1)` the node `:stmt1`, then say `:stmt1 :confidence 0.9`.",
    prerequisites: ["triple", "entity"], introducedIn: "sb-modeling" },
  { id: "named-graph", term: "named graph", layer: "system", band: "practitioner",
    short: "A @c{knowledge-graph} given its own @c{iri}, so facts from different sources, contexts, or trust levels stay separate and queryable.",
    example: "extracted triples in graph `:fromPaper`, your own assertions in `:mine`.",
    prerequisites: ["knowledge-graph", "iri"], introducedIn: "sb-modeling" },
  { id: "temporal-validity", term: "temporal validity", layer: "data", band: "practitioner",
    short: "A fact that holds only over a time interval or context — modeled with @c{reification} or a @c{named-graph}, not a bare @c{triple}.",
    example: "`(Ada, livesIn, London)` valid 1843–1852.",
    prerequisites: ["reification", "named-graph"], introducedIn: "sb-modeling" },

  // ============ sb-onto: ontologies ============
  { id: "class", term: "class", layer: "schema",
    short: "A category of @c{entity}s — the *kind* a thing is.",
    example: "`Person`, `Note`, `Paper`.",
    prerequisites: ["entity"], contrasts: ["entity"], introducedIn: "sb-onto" },
  { id: "instance", term: "instance", layer: "schema",
    short: "An @c{entity} asserted to be a member of a @c{class}.",
    example: "`Ada a Person`.",
    prerequisites: ["entity", "class"], introducedIn: "sb-onto" },
  { id: "subclass", term: "subclass", layer: "schema",
    short: "An is-a relationship between @c{class}es: subclass members are superclass members.",
    example: "`Researcher ⊑ Person`.",
    prerequisites: ["class"], contrasts: ["sameas"], introducedIn: "sb-onto" },
  { id: "property-schema", term: "property (schema)", layer: "schema",
    short: "A @c{relation} declared in the schema with a domain and range — what kind of thing can link to what.",
    example: "`wrote: Person → Note`.",
    prerequisites: ["relation", "class"], introducedIn: "sb-onto" },
  { id: "tbox", term: "TBox", layer: "schema",
    short: "The terminology box: the schema — @c{class}es, @c{property-schema} declarations, and axioms.",
    example: "`Researcher ⊑ Person`, `wrote: Person→Note`.",
    prerequisites: ["class", "property-schema"], contrasts: ["abox"], introducedIn: "sb-onto" },
  { id: "abox", term: "ABox", layer: "data",
    short: "The assertion box: the data — facts about specific @c{instance}s.",
    example: "`:Ada a :Researcher .`",
    prerequisites: ["instance"], contrasts: ["tbox"], introducedIn: "sb-onto" },
  { id: "disjointness", term: "disjointness", layer: "schema", band: "foundations",
    short: "An @c{axiom} that two @c{class}es share no members — so claiming something is *both* is a contradiction.",
    example: "`Person` and `Note` disjoint ⇒ nothing is both a Person and a Note.",
    prerequisites: ["class", "axiom"], introducedIn: "sb-onto-eng" },
  { id: "subproperty", term: "subproperty", layer: "schema", band: "foundations",
    short: "A @c{property-schema} more specific than another: every `hasMother` link is also a `hasParent` link.",
    example: "`hasMother ⊑ hasParent`.",
    prerequisites: ["property-schema"], introducedIn: "sb-onto-eng" },
  { id: "object-property", term: "object property", layer: "schema", band: "foundations",
    short: "A @c{property-schema} whose values are @c{entity}s — a link between two things.",
    example: "`wrote: Person → Note` (object is an entity).",
    prerequisites: ["property-schema", "entity"], contrasts: ["datatype-property"], introducedIn: "sb-onto-eng" },
  { id: "datatype-property", term: "datatype property", layer: "schema", band: "foundations",
    short: "A @c{property-schema} whose values are @c{literal}s — a data value on a thing.",
    example: "`birthYear: Person → integer` (object is a literal).",
    prerequisites: ["property-schema", "literal"], contrasts: ["object-property"], introducedIn: "sb-onto-eng" },
  { id: "equivalence", term: "equivalence", layer: "schema", band: "practitioner",
    short: "Two @c{class}es (or properties) that are necessarily the same set — @c{subclass} both ways.",
    example: "`Human ≡ Person`.",
    prerequisites: ["subclass"], introducedIn: "sb-onto-eng" },
  { id: "ontology", term: "ontology", layer: "schema",
    short: "The schema + axioms (the @c{tbox} plus the @c{subclass} hierarchy and @c{property-schema} rules) that give your knowledge graph *meaning*.",
    example: "An OWL/RDFS ontology.",
    prerequisites: ["tbox", "subclass", "property-schema"], contrasts: ["knowledge-graph", "taxonomy"], introducedIn: "sb-onto" },
  { id: "taxonomy", term: "taxonomy", layer: "schema", band: "foundations",
    short: "A pure classification hierarchy — broader/narrower @c{subclass} links — without the *richer* axioms (properties, restrictions, disjointness) of a full ontology. An ontology is not just a taxonomy.",
    example: "`Animal > Mammal > Dog` — just is-a nesting.",
    prerequisites: ["subclass"], contrasts: ["ontology"], introducedIn: "sb-onto-eng" },
  { id: "thesaurus", term: "thesaurus", layer: "schema", band: "practitioner",
    short: "A controlled vocabulary with broader / narrower / related links (SKOS) — richer than a @c{taxonomy}, looser than an ontology (no logical axioms).",
    example: "SKOS: `:CT skos:broader :Mathematics`.",
    prerequisites: ["taxonomy"], introducedIn: "sb-onto-eng" },
  { id: "competency-question", term: "competency question", layer: "schema", band: "foundations",
    short: "A question your @c{ontology} must be able to answer — the design driver you write *before* modeling.",
    example: "\"Which notes cite a paper Ada wrote?\" — if the model can't answer it, the model is wrong.",
    prerequisites: ["ontology"], introducedIn: "sb-onto-eng" },
  { id: "ontology-reuse", term: "ontology reuse", layer: "schema", band: "practitioner",
    short: "Aligning to or importing an existing @c{ontology} (FOAF, schema.org, SUMO) instead of inventing terms — so your second brain interoperates.",
    example: "use `foaf:Person` rather than your own `:Person`.",
    prerequisites: ["ontology"], introducedIn: "sb-onto-eng" },

  // ============ sb-reasoning: logic & reasoning ============
  { id: "axiom", term: "axiom", layer: "logic",
    short: "A statement taken as given (not derived) — a @c{subclass} fact or a @c{property-schema} declaration is an axiom; derived facts are not.",
    example: "`Researcher ⊑ Person` is an axiom.",
    prerequisites: ["subclass", "property-schema"], introducedIn: "sb-onto" },
  { id: "entailment", term: "entailment", layer: "logic",
    short: "A fact that follows logically from your @c{triple}s + @c{ontology} + @c{axiom}s — derivable even though you never stored it.",
    example: "`Ada:Person` from `Ada:Researcher` + `Researcher⊑Person`.",
    prerequisites: ["triple", "ontology", "axiom"], contrasts: ["hallucination", "validation"], introducedIn: "sb-reasoning",
    microQuiz: [{ id: "mq-ent", type: "true-false", prompt: "True or false: entailment is derived (it follows logically), not looked up.", correct: true, explanation: "A reasoner derives entailed facts from data + axioms." }] },
  { id: "reasoner", term: "reasoner", layer: "logic",
    short: "Software that computes @c{entailment}s, classifies entities, and detects (entailed) contradictions from an @c{ontology} + data.",
    example: "HermiT, ELK (OWL reasoners).",
    prerequisites: ["entailment", "ontology"], contrasts: ["llm-extraction"], introducedIn: "sb-reasoning" },
  { id: "open-world-assumption", term: "open-world assumption", layer: "logic",
    short: "Absence of a fact means *unknown*, not *false* (RDF/OWL). The #1 modeling gotcha.",
    example: "No `Ada knows Bob` triple ≠ Ada doesn't know Bob.",
    prerequisites: ["entailment"], contrasts: ["closed-world-assumption"], introducedIn: "sb-reasoning" },
  { id: "closed-world-assumption", term: "closed-world assumption", layer: "logic",
    short: "Absence of a fact means *false* (databases, SPARQL `NOT EXISTS`). The opposite default to OWL.",
    example: "A SQL query returns no row ⇒ treated as 'no such fact'.",
    prerequisites: ["entailment"], contrasts: ["open-world-assumption"], introducedIn: "sb-reasoning" },
  { id: "consistency", term: "consistency", layer: "logic",
    short: "Whether your @c{axiom}s + data contain no contradiction — a @c{reasoner} can check it.",
    example: "The bad triple `note_1 wrote Ada` entails `note_1 a Person` (domain of `wrote`); with `Person`/`Note` @c{disjointness} and `note_1 a Note`, that's inconsistent.",
    prerequisites: ["reasoner", "axiom", "disjointness"], introducedIn: "sb-reasoning" },
  { id: "transitive-property", term: "transitive property", layer: "logic", band: "practitioner",
    short: "A @c{property-schema} where A→B and B→C @c{entailment}s A→C — chains close automatically.",
    example: "`ancestorOf` transitive: Ada ancestorOf Bob, Bob ancestorOf Cy ⇒ Ada ancestorOf Cy.",
    prerequisites: ["property-schema", "entailment"], introducedIn: "sb-expressivity" },
  { id: "property-chain", term: "property chain", layer: "logic", band: "practitioner",
    short: "An @c{axiom} that *composing* two @c{property-schema}s @c{entailment}s a third — 'the father of my father is my grandfather'.",
    example: "`hasParent ∘ hasParent ⊑ hasGrandparent`.",
    prerequisites: ["property-schema", "axiom", "entailment"], introducedIn: "sb-expressivity" },
  { id: "inverse-property", term: "inverse property", layer: "logic", band: "practitioner",
    short: "A @c{property-schema} declared the reverse of another, so asserting one @c{entailment}s the other.",
    example: "`hasParent` inverse of `hasChild`: `Ada hasChild Bob` ⇒ `Bob hasParent Ada`.",
    prerequisites: ["property-schema", "entailment"], introducedIn: "sb-expressivity" },
  { id: "symmetric-property", term: "symmetric property", layer: "logic", band: "practitioner",
    short: "A @c{property-schema} that holds both ways: A→B @c{entailment}s B→A.",
    example: "`siblingOf`: `Ada siblingOf Bob` ⇒ `Bob siblingOf Ada`.",
    prerequisites: ["property-schema", "entailment"], introducedIn: "sb-expressivity" },
  { id: "cardinality-restriction", term: "cardinality restriction", layer: "logic", band: "practitioner",
    short: "An @c{axiom} bounding how many values a @c{property-schema} may take — at-least, at-most, or exactly N.",
    example: "A `Person` has exactly one `biologicalMother`.",
    prerequisites: ["property-schema", "axiom"], introducedIn: "sb-expressivity" },
  { id: "functional-property", term: "functional property", layer: "logic", band: "practitioner",
    short: "A @c{cardinality-restriction} of at-most-one. Two values *known to differ* (e.g. distinct literals) are a @c{consistency} violation; two differently-*named* individuals are instead inferred to be the same thing (open-world, no unique names).",
    example: "`hasBirthYear` functional: 1815 and 1816 are distinct literals, so asserting both for one person is inconsistent.",
    prerequisites: ["cardinality-restriction", "property-schema", "consistency"], introducedIn: "sb-expressivity" },
  { id: "existential-restriction", term: "existential restriction", layer: "logic", band: "practitioner",
    short: "A @c{class} expression: the things with *at least one* @c{property-schema} value of a given type (someValuesFrom).",
    example: "`hasChild some Person` — the class of things with at least one child.",
    prerequisites: ["class", "property-schema"], introducedIn: "sb-expressivity" },
  { id: "universal-restriction", term: "universal restriction", layer: "logic", band: "practitioner",
    short: "A @c{class} expression: the things *all* of whose @c{property-schema} values are of a type (allValuesFrom). Two gotchas: it is *vacuously* true for things with no such value (an empty 'for all'), and under the @c{open-world-assumption} a reasoner won't classify something *into* it from partial data — unknown other values might violate it.",
    example: "`eats only Plant` — a known plant-eater isn't auto-classed vegan (there may be unseen non-plant meals), while something with no `eats` asserted trivially qualifies.",
    prerequisites: ["class", "property-schema", "open-world-assumption"], introducedIn: "sb-expressivity" },
  { id: "defined-class", term: "defined class", layer: "logic", band: "practitioner",
    short: "A @c{class} given necessary-*and*-sufficient conditions (an @c{equivalence}, not just a @c{subclass}), so a @c{reasoner} can *infer* membership — classification.",
    example: "Define `Parent ≡ hasChild some Person`; assert `Ada hasChild Bob` and `Bob a Person`, and the reasoner infers `Ada a Parent`.",
    prerequisites: ["equivalence", "existential-restriction", "reasoner"], introducedIn: "sb-expressivity" },
  { id: "description-logic", term: "description logic", layer: "logic", band: "practitioner",
    short: "A family of *decidable fragments* of first-order logic that found OWL — @c{class}es as concepts, @c{property-schema}s as roles, @c{subclass} as subsumption.",
    example: "OWL 2 DL corresponds to the DL `SROIQ`; the EL/QL/RL profiles trade expressivity for faster reasoning.",
    prerequisites: ["class", "property-schema", "subclass"], introducedIn: "sb-reasoning" },
  { id: "rule", term: "inference rule (SWRL)", layer: "logic", band: "practitioner",
    short: "An if-then rule that *derives* new @c{triple}s from existing ones — open-world inference (SWRL, an OWL rule extension), the opposite of a validation shape, which only flags.",
    example: "`hasParent(x,y) ∧ hasParent(y,z) ⇒ hasGrandparent(x,z)`.",
    prerequisites: ["triple", "ontology"], contrasts: ["validation"], introducedIn: "sb-reasoning" },
  { id: "validation", term: "validation", layer: "logic", band: "foundations",
    short: "Checking data against constraints (shapes) and *reporting* violations — closed-world, and crucially **not** @c{entailment}: validation never derives new facts, it only flags bad ones.",
    example: "A shape: every `Note` must have a `title`; data without one is reported, not repaired.",
    prerequisites: ["entailment", "closed-world-assumption"], contrasts: ["entailment", "rule"], introducedIn: "sb-reasoning" },

  // ============ sb-neural: the neural side ============
  { id: "embedding", term: "embedding", layer: "neural",
    short: "A learned vector representation of a thing (an @c{entity}, a word, a document, a relation…) that places similar things close together — captures fuzzy similarity, with no guarantees.",
    example: "A 768-dim vector for `category_theory`.",
    prerequisites: ["entity"], contrasts: ["triple"], introducedIn: "sb-neural" },
  { id: "similarity", term: "similarity", layer: "neural",
    short: "Closeness of two @c{embedding}s — 'these are about the same thing', fuzzily.",
    example: "cosine(`CT_note`, `monad_note`) = 0.81.",
    prerequisites: ["embedding"], introducedIn: "sb-neural" },
  { id: "kg-embedding", term: "KG embedding", layer: "neural", band: "practitioner",
    short: "An @c{embedding} that encodes @c{knowledge-graph} structure, for similarity and link prediction.",
    example: "TransE, ComplEx.",
    prerequisites: ["embedding", "knowledge-graph"], introducedIn: "sb-neural" },
  { id: "llm-extraction", term: "LLM extraction", layer: "neural",
    short: "Using an LLM to turn unstructured text into @c{triple}s — powerful, but unverified.",
    example: "'Ada wrote a note on CT' → `(Ada, wrote, note)`.",
    prerequisites: ["triple"], contrasts: ["reasoner"], introducedIn: "sb-neural" },
  { id: "hallucination", term: "hallucination", layer: "neural",
    short: "Confident-but-wrong output from @c{llm-extraction} — a fact that looks fine but isn't supported.",
    example: "Inventing a citation that doesn't exist.",
    prerequisites: ["llm-extraction"], contrasts: ["entailment"], introducedIn: "sb-neural" },

  // ============ sb-identity: identity & resolution ============
  { id: "identifier", term: "identifier", layer: "data",
    short: "The name you use for an @c{entity}. Two identifiers may or may not denote the same thing.",
    example: "`:Ada`, `:A_Lovelace`, `wd:Q7259`.",
    prerequisites: ["entity"], introducedIn: "sb-neural" },
  { id: "sameas", term: "sameAs", layer: "schema",
    short: "An assertion that two @c{identifier}s denote the *same* @c{entity}. Not subclass — same individual.",
    example: "`:Ada owl:sameAs wd:Q7259 .`",
    prerequisites: ["identifier", "entity"], contrasts: ["subclass"], introducedIn: "sb-neural" },
  { id: "entity-resolution", term: "entity resolution", layer: "system",
    short: "Deciding when two records are the same @c{entity} — a heuristic that *proposes* @c{sameas} links from exact keys + fuzzy @c{similarity} (fuzzy match has no logical semantics on its own).",
    example: "Merging `Ada Lovelace` and `A. Lovelace` into one node.",
    prerequisites: ["entity", "sameas", "similarity"], introducedIn: "sb-neural" },

  // ============ sb-neurosymbolic: combine ============
  { id: "neurosymbolic", term: "neurosymbolic", layer: "system",
    short: "Combining learned and explicit: let @c{llm-extraction} (neural) propose, and the @c{ontology} + @c{reasoner} (symbolic) verify and constrain.",
    example: "LLM drafts triples; the reasoner flags contradictions and shape validation rejects ill-shaped ones.",
    prerequisites: ["llm-extraction", "ontology", "reasoner"], introducedIn: "sb-neurosymbolic",
    microQuiz: [{ id: "mq-ns", type: "multiple-choice", prompt: "What does neurosymbolic mean for a second brain?", options: ["only neural", "only logic", "neural proposes, symbolic verifies/constrains", "no AI"], correct: 2, explanation: "Combine: neural proposes; symbolic verifies." }] },
  { id: "ontology-grounded-extraction", term: "ontology-grounded extraction", layer: "system",
    short: "@c{llm-extraction} constrained to the @c{ontology}'s classes & properties, so output is on-schema by construction.",
    example: "Force the LLM to emit only declared relations.",
    prerequisites: ["llm-extraction", "ontology"], introducedIn: "sb-neurosymbolic" },
  { id: "shacl-validation", term: "SHACL validation", layer: "system", band: "foundations",
    short: "A @c{validation} check (SHACL) of extracted data against shape constraints — closed-world and *separate from OWL reasoning*: it reports shape violations (a missing title, a wrong type) rather than deriving or entailing facts. The verify step that catches bad @c{llm-extraction}.",
    example: "Reject any `Note` missing a `title`.",
    prerequisites: ["validation", "llm-extraction"], introducedIn: "sb-neurosymbolic" },
  { id: "propose-verify", term: "propose & verify", layer: "system",
    short: "The neurosymbolic loop: @c{llm-extraction} proposes; the @c{reasoner} checks consistency and @c{shacl-validation} checks shapes — the heart of @c{neurosymbolic} for a trustworthy brain.",
    example: "Draft → validate → accept/repair → store.",
    prerequisites: ["llm-extraction", "reasoner", "shacl-validation", "neurosymbolic"], introducedIn: "sb-neurosymbolic" },
  { id: "provenance", term: "provenance", layer: "system",
    short: "Recording where each @c{triple} came from (source, extractor, confidence) — essential once neural and symbolic facts mix. Attach it by reifying the statement or using a named graph.",
    example: "`note_1 wasDerivedFrom paper.pdf, by gpt-5-mini`.",
    prerequisites: ["triple"], introducedIn: "sb-neurosymbolic" },

  // ============ sb-construction: building the graph from text ============
  { id: "ner", term: "named entity recognition", layer: "neural", band: "practitioner",
    short: "Spotting entity *mentions* in raw text — the first step of turning notes into @c{entity}s.",
    example: "In \"Ada wrote to Babbage\", tag `Ada` and `Babbage` as mentions.",
    prerequisites: ["entity", "llm-extraction"], introducedIn: "sb-construction" },
  { id: "entity-linking", term: "entity linking", layer: "neural", band: "practitioner",
    short: "Mapping a text mention to the *right* canonical @c{entity} (disambiguation), not just any match.",
    example: "\"Ada\" → `:Ada_Lovelace`, not some other Ada.",
    prerequisites: ["ner", "entity-resolution"], introducedIn: "sb-construction" },
  { id: "relation-extraction", term: "relation extraction", layer: "neural", band: "practitioner",
    short: "Pulling typed @c{relation}s between mentions out of text — the verbs of the graph.",
    example: "\"Ada wrote a note\" → `(Ada, wrote, note)`.",
    prerequisites: ["ner", "relation"], introducedIn: "sb-construction" },
  { id: "coreference", term: "coreference resolution", layer: "neural", band: "practitioner",
    short: "Deciding that \"she\", \"Lovelace\", \"the author\" all refer to one @c{entity} within a text.",
    example: "\"Ada … she … the countess\" → all `:Ada_Lovelace`.",
    prerequisites: ["ner"], introducedIn: "sb-construction" },
  { id: "knowledge-fusion", term: "knowledge fusion", layer: "system", band: "practitioner",
    short: "Merging facts about the same @c{entity} from many sources into one view — tracking @c{provenance} as you go.",
    example: "Two papers + your notes about Ada → one merged, sourced profile.",
    prerequisites: ["entity-resolution", "provenance"], introducedIn: "sb-construction" },
  { id: "conflict-resolution", term: "conflict resolution", layer: "system", band: "practitioner",
    short: "When sources disagree, deciding which @c{triple} to trust — by recency, source reliability, or @c{provenance}.",
    example: "One source says born 1815, another 1816 → pick by source quality.",
    prerequisites: ["knowledge-fusion"], introducedIn: "sb-construction" },

  // ============ sb-llm-kg: using your brain with an LLM ============
  { id: "kg-rag", term: "KG-grounded RAG", layer: "system", band: "practitioner",
    short: "Retrieval-augmented generation over your graph: @c{query} the relevant @c{triple}s, then let the LLM answer *grounded* in them — fewer @c{hallucination}s.",
    example: "Q → fetch Ada's notes → LLM answers citing them.",
    prerequisites: ["query", "llm-extraction", "hallucination"], introducedIn: "sb-llm-kg" },
  { id: "text-to-sparql", term: "text-to-SPARQL", layer: "system", band: "practitioner",
    short: "Translating a natural-language question into @c{sparql} over your @c{rdf-graph} — a query you can run, not a guess.",
    example: "\"What did Ada write?\" → `SELECT ?n WHERE { :Ada :wrote ?n }`.",
    prerequisites: ["sparql", "llm-extraction"], introducedIn: "sb-llm-kg" },
  { id: "schema-induction", term: "schema induction", layer: "system", band: "practitioner",
    short: "Proposing @c{class}es and @c{property-schema}s from a corpus — bootstrapping an @c{ontology} from your data (then a human curates).",
    example: "Notes about people/notes → suggest `Person`, `Note`, `wrote`.",
    prerequisites: ["ontology", "llm-extraction"], introducedIn: "sb-llm-kg" },
  { id: "agent-memory-graph", term: "agent memory graph", layer: "system", band: "practitioner",
    short: "Using a @c{knowledge-graph} as an agent's structured long-term memory — query it, write back to it, reason over it.",
    example: "An assistant stores what it learns as triples and recalls them later.",
    prerequisites: ["knowledge-graph", "llm-extraction"], introducedIn: "sb-llm-kg" },

  // ============ sb-kgml: learning over the graph ============
  { id: "scoring-function", term: "scoring function", layer: "neural", band: "expert",
    short: "A @c{kg-embedding} model's plausibility score for a @c{triple} — high for likely-true, low for likely-false.",
    example: "score(`Ada`, `wrote`, `note_1`) = 0.92.",
    prerequisites: ["kg-embedding"], introducedIn: "sb-kgml" },
  { id: "transe", term: "TransE", layer: "neural", band: "expert",
    short: "A translational @c{kg-embedding}: a @c{relation} is a *vector translation* h + r ≈ t, so the @c{scoring-function} rewards triples whose vectors line up.",
    example: "`Ada` + `wrote` ≈ `note_1` in vector space.",
    prerequisites: ["kg-embedding", "scoring-function"], introducedIn: "sb-kgml" },
  { id: "negative-sampling", term: "negative sampling", layer: "neural", band: "expert",
    short: "Training a @c{kg-embedding} by contrasting true @c{triple}s against *corrupted* false ones, so the @c{scoring-function} learns to separate them.",
    example: "Corrupt `(Ada, wrote, note_1)` → `(Ada, wrote, Babbage)` as a negative.",
    prerequisites: ["scoring-function"], introducedIn: "sb-kgml" },
  { id: "link-prediction", term: "link prediction", layer: "neural", band: "expert",
    short: "Predicting missing @c{triple}s from graph structure — *completing* your brain by scoring candidate edges with a @c{kg-embedding}.",
    example: "The model suggests `(Ada, knows, Babbage)` was never stored but likely.",
    prerequisites: ["kg-embedding", "scoring-function"], introducedIn: "sb-kgml" },
  { id: "triple-classification", term: "triple classification", layer: "neural", band: "expert",
    short: "Deciding whether a candidate @c{triple} is true — thresholding a @c{scoring-function}; the verify side of @c{link-prediction}.",
    example: "Is `(Ada, wrote, note_9)` true? score 0.3 → no.",
    prerequisites: ["scoring-function", "link-prediction"], introducedIn: "sb-kgml" },
];

export const CONCEPT_GRAPH: ConceptGraph = { concepts: CONCEPTS };

export const CONCEPT_BY_ID: Record<string, Concept> = Object.fromEntries(
  CONCEPTS.map((c) => [c.id, c]),
);

/** Per-edge justification for every prerequisite, keyed `"concept>prerequisite"`. */
export const PREREQ_WHY: Record<string, string> = {
  "relation>entity": "a relation links entities",
  "iri>entity": "an IRI is a global name for an entity",
  "iri>relation": "an IRI also names relations, not just entities",
  "triple>entity": "a triple's subject and object are entities",
  "triple>relation": "a triple's predicate is a relation",
  "literal>triple": "a literal is the object value of a triple",
  "knowledge-graph>triple": "a knowledge graph is a set of triples",
  "property-graph>knowledge-graph": "a property graph is one model of a knowledge graph",
  "rdf-graph>knowledge-graph": "an RDF graph is one model of a knowledge graph",
  "rdf-graph>triple": "RDF is built from triples",
  "rdf-graph>iri": "RDF names every node/edge with an IRI",
  "query>knowledge-graph": "a query retrieves matches from a knowledge graph",
  "basic-graph-pattern>query": "a graph pattern is how a query is expressed",
  "basic-graph-pattern>triple": "a pattern is triples with variables",
  "sparql>rdf-graph": "SPARQL queries RDF graphs",
  "sparql>basic-graph-pattern": "SPARQL is built on graph patterns",
  "cypher>property-graph": "Cypher queries property graphs",
  "cypher>query": "Cypher is a query language",
  "property-path>basic-graph-pattern": "a property path extends a graph pattern with repetition",
  "class>entity": "a class is a category of entities",
  "instance>entity": "an instance is an entity",
  "instance>class": "an instance is a member of a class",
  "subclass>class": "subclass is a relationship between two classes",
  "property-schema>relation": "a schema property is a declared relation",
  "property-schema>class": "a property's domain and range are classes",
  "tbox>class": "the TBox declares the classes",
  "tbox>property-schema": "the TBox declares the properties",
  "abox>instance": "the ABox is the set of instance assertions",
  "disjointness>class": "disjointness is an axiom about two classes",
  "disjointness>axiom": "disjointness is a kind of axiom",
  "subproperty>property-schema": "a subproperty is a more specific property",
  "object-property>property-schema": "an object property is a property whose values are entities",
  "object-property>entity": "its values are entities",
  "datatype-property>property-schema": "a datatype property is a property whose values are literals",
  "datatype-property>literal": "its values are literals",
  "n-ary-relation>triple": "an n-ary relation can't be a single binary triple",
  "n-ary-relation>entity": "it is modeled via an intermediate entity",
  "reification>triple": "reification turns a triple into a describable node",
  "reification>entity": "the reified statement is an entity",
  "named-graph>knowledge-graph": "a named graph is a knowledge graph with an identity",
  "named-graph>iri": "the graph is named by an IRI",
  "temporal-validity>reification": "time/context is attached via reification",
  "temporal-validity>named-graph": "or via a named graph per context",
  "equivalence>subclass": "equivalence is subclass in both directions",
  "ontology>tbox": "an ontology is the TBox plus axioms",
  "ontology>subclass": "an ontology includes the subclass hierarchy",
  "ontology>property-schema": "an ontology declares the properties",
  "taxonomy>subclass": "a taxonomy is a subclass hierarchy",
  "thesaurus>taxonomy": "a thesaurus extends a taxonomy with related links",
  "competency-question>ontology": "a competency question is what the ontology must answer",
  "ontology-reuse>ontology": "reuse means importing/aligning an existing ontology",
  "axiom>subclass": "a subclass statement is a kind of axiom",
  "axiom>property-schema": "a property declaration is a kind of axiom",
  "entailment>triple": "entailment produces new triples",
  "entailment>ontology": "entailment is relative to the ontology's meaning",
  "entailment>axiom": "entailment follows from the axioms",
  "reasoner>entailment": "a reasoner's job is to compute entailments",
  "reasoner>ontology": "a reasoner works over an ontology",
  "open-world-assumption>entailment": "OWA shapes what counts as entailed (unknown vs false)",
  "closed-world-assumption>entailment": "CWA shapes what counts as entailed (unknown vs false)",
  "consistency>reasoner": "a reasoner checks consistency",
  "consistency>axiom": "consistency is about the axioms not contradicting",
  "consistency>disjointness": "a disjointness axiom is what makes the example contradiction detectable",
  "validation>entailment": "validation is defined by contrast with inference/entailment",
  "validation>closed-world-assumption": "validation is closed-world (missing = violation)",
  "transitive-property>property-schema": "a transitive property is a property with an axiom",
  "transitive-property>entailment": "transitivity licenses entailments (chains close)",
  "property-chain>property-schema": "a chain composes properties",
  "property-chain>axiom": "a property-chain rule is an axiom",
  "property-chain>entailment": "the chain entails the composed relation",
  "inverse-property>property-schema": "an inverse relates two properties",
  "inverse-property>entailment": "the inverse entails the reverse direction",
  "symmetric-property>property-schema": "symmetry is a property characteristic",
  "symmetric-property>entailment": "symmetry entails the reverse direction",
  "cardinality-restriction>property-schema": "cardinality bounds a property's values",
  "cardinality-restriction>axiom": "a cardinality bound is an axiom",
  "functional-property>cardinality-restriction": "functional is at-most-one cardinality",
  "functional-property>property-schema": "functional is a property characteristic",
  "functional-property>consistency": "two known-distinct values violate consistency",
  "existential-restriction>class": "a restriction defines a class",
  "existential-restriction>property-schema": "the restriction is over a property",
  "universal-restriction>class": "a restriction defines a class",
  "universal-restriction>property-schema": "the restriction is over a property",
  "universal-restriction>open-world-assumption": "OWA blocks positive classification into a ∀-restriction from partial data",
  "defined-class>equivalence": "a defined class uses equivalence, not just subclass",
  "defined-class>existential-restriction": "the definition is a restriction",
  "defined-class>reasoner": "the reasoner infers membership (classification)",
  "description-logic>class": "DL concepts are classes",
  "description-logic>property-schema": "DL roles are properties",
  "description-logic>subclass": "DL subsumption is the subclass relation",
  "rule>triple": "rules fire over and produce triples",
  "rule>ontology": "rules complement the ontology's axioms",
  "embedding>entity": "an embedding represents an entity",
  "similarity>embedding": "similarity compares embeddings",
  "kg-embedding>embedding": "a KG embedding is an embedding",
  "kg-embedding>knowledge-graph": "a KG embedding encodes graph structure",
  "llm-extraction>triple": "extraction produces triples",
  "hallucination>llm-extraction": "hallucination is a failure mode of extraction",
  "identifier>entity": "an identifier names an entity",
  "sameas>identifier": "sameAs relates two identifiers",
  "sameas>entity": "sameAs says they denote the same entity",
  "entity-resolution>entity": "entity resolution decides entity identity",
  "entity-resolution>sameas": "resolution produces sameAs links",
  "entity-resolution>similarity": "resolution uses fuzzy similarity to find candidates",
  "neurosymbolic>llm-extraction": "neurosymbolic uses neural extraction to propose",
  "neurosymbolic>ontology": "neurosymbolic uses the ontology to constrain/verify",
  "neurosymbolic>reasoner": "neurosymbolic uses the reasoner to verify",
  "ontology-grounded-extraction>llm-extraction": "it is extraction, constrained",
  "ontology-grounded-extraction>ontology": "the ontology supplies the constraints",
  "shacl-validation>validation": "SHACL is a concrete validation language",
  "shacl-validation>llm-extraction": "validation checks extracted data",
  "propose-verify>llm-extraction": "the propose step is extraction",
  "propose-verify>reasoner": "the verify step uses the reasoner for consistency",
  "propose-verify>shacl-validation": "the verify step uses shape validation",
  "propose-verify>neurosymbolic": "propose-verify is the core neurosymbolic loop",
  "provenance>triple": "provenance annotates triples with their source",
  "ner>entity": "NER finds entity mentions",
  "ner>llm-extraction": "NER is a step of extraction",
  "entity-linking>ner": "linking maps the mentions NER found",
  "entity-linking>entity-resolution": "linking is resolution against a canonical set",
  "relation-extraction>ner": "relations connect the mentions NER found",
  "relation-extraction>relation": "it extracts typed relations",
  "coreference>ner": "coreference groups mentions of one entity",
  "knowledge-fusion>entity-resolution": "fusion merges records resolution says are the same",
  "knowledge-fusion>provenance": "fusion tracks where each merged fact came from",
  "conflict-resolution>knowledge-fusion": "conflicts arise when fusing disagreeing sources",
  "kg-rag>query": "RAG queries the graph for relevant facts",
  "kg-rag>hallucination": "RAG targets the hallucination failure mode",
  "kg-rag>llm-extraction": "RAG feeds retrieved facts to the LLM",
  "text-to-sparql>sparql": "it produces a SPARQL query",
  "text-to-sparql>llm-extraction": "the LLM does the translation",
  "schema-induction>ontology": "it proposes ontology terms",
  "schema-induction>llm-extraction": "the LLM induces the schema from text",
  "agent-memory-graph>knowledge-graph": "the memory is a knowledge graph",
  "agent-memory-graph>llm-extraction": "the agent writes memory via extraction",
  "scoring-function>kg-embedding": "the score comes from the embedding model",
  "transe>kg-embedding": "TransE is a KG embedding model",
  "transe>scoring-function": "TransE defines a scoring function",
  "negative-sampling>scoring-function": "it trains the scoring function",
  "link-prediction>kg-embedding": "prediction uses the embedding",
  "link-prediction>scoring-function": "it scores candidate edges",
  "triple-classification>scoring-function": "it thresholds the score",
  "triple-classification>link-prediction": "classification is the verify side of prediction",
};

export function prereqWhy(concept: string, prereq: string): string | undefined {
  return PREREQ_WHY[`${concept}>${prereq}`];
}

/** Semantic KIND of each prerequisite edge (ADR-0005). Annotation only. */
export const PREREQ_KINDS = ["is-a", "part-of", "defined-via", "operates-on", "refines", "assumes"] as const;
export type PrereqKind = (typeof PREREQ_KINDS)[number];

export const PREREQ_KIND: Record<string, PrereqKind> = {
  "relation>entity": "operates-on",
  "iri>entity": "operates-on",
  "iri>relation": "operates-on",
  "triple>entity": "defined-via",
  "triple>relation": "defined-via",
  "literal>triple": "part-of",
  "knowledge-graph>triple": "part-of",
  "property-graph>knowledge-graph": "is-a",
  "rdf-graph>knowledge-graph": "is-a",
  "rdf-graph>triple": "defined-via",
  "rdf-graph>iri": "defined-via",
  "query>knowledge-graph": "operates-on",
  "basic-graph-pattern>query": "part-of",
  "basic-graph-pattern>triple": "defined-via",
  "sparql>rdf-graph": "operates-on",
  "sparql>basic-graph-pattern": "is-a",
  "cypher>property-graph": "operates-on",
  "cypher>query": "is-a",
  "property-path>basic-graph-pattern": "refines",
  "class>entity": "operates-on",
  "instance>entity": "is-a",
  "instance>class": "defined-via",
  "subclass>class": "operates-on",
  "property-schema>relation": "is-a",
  "property-schema>class": "defined-via",
  "tbox>class": "part-of",
  "tbox>property-schema": "part-of",
  "abox>instance": "part-of",
  "disjointness>class": "operates-on",
  "disjointness>axiom": "is-a",
  "subproperty>property-schema": "refines",
  "object-property>property-schema": "is-a",
  "object-property>entity": "operates-on",
  "datatype-property>property-schema": "is-a",
  "datatype-property>literal": "operates-on",
  "n-ary-relation>triple": "refines",
  "n-ary-relation>entity": "operates-on",
  "reification>triple": "operates-on",
  "reification>entity": "is-a",
  "named-graph>knowledge-graph": "is-a",
  "named-graph>iri": "operates-on",
  "temporal-validity>reification": "defined-via",
  "temporal-validity>named-graph": "defined-via",
  "equivalence>subclass": "defined-via",
  "ontology>tbox": "part-of",
  "ontology>subclass": "part-of",
  "ontology>property-schema": "part-of",
  "taxonomy>subclass": "is-a",
  "thesaurus>taxonomy": "refines",
  "competency-question>ontology": "assumes",
  "ontology-reuse>ontology": "operates-on",
  "axiom>subclass": "is-a",
  "axiom>property-schema": "is-a",
  "entailment>triple": "operates-on",
  "entailment>ontology": "defined-via",
  "entailment>axiom": "defined-via",
  "reasoner>entailment": "operates-on",
  "reasoner>ontology": "operates-on",
  "open-world-assumption>entailment": "refines",
  "closed-world-assumption>entailment": "refines",
  "consistency>reasoner": "defined-via",
  "consistency>axiom": "operates-on",
  "consistency>disjointness": "operates-on",
  "validation>entailment": "defined-via",
  "validation>closed-world-assumption": "assumes",
  "transitive-property>property-schema": "refines",
  "transitive-property>entailment": "operates-on",
  "property-chain>property-schema": "operates-on",
  "property-chain>axiom": "is-a",
  "property-chain>entailment": "operates-on",
  "inverse-property>property-schema": "refines",
  "inverse-property>entailment": "operates-on",
  "symmetric-property>property-schema": "refines",
  "symmetric-property>entailment": "operates-on",
  "cardinality-restriction>property-schema": "operates-on",
  "cardinality-restriction>axiom": "is-a",
  "functional-property>cardinality-restriction": "is-a",
  "functional-property>property-schema": "refines",
  "functional-property>consistency": "operates-on",
  "existential-restriction>class": "is-a",
  "existential-restriction>property-schema": "operates-on",
  "universal-restriction>class": "is-a",
  "universal-restriction>property-schema": "operates-on",
  "universal-restriction>open-world-assumption": "assumes",
  "defined-class>equivalence": "defined-via",
  "defined-class>existential-restriction": "defined-via",
  "defined-class>reasoner": "operates-on",
  "description-logic>class": "defined-via",
  "description-logic>property-schema": "defined-via",
  "description-logic>subclass": "defined-via",
  "rule>triple": "operates-on",
  "rule>ontology": "assumes",
  "embedding>entity": "operates-on",
  "similarity>embedding": "operates-on",
  "kg-embedding>embedding": "is-a",
  "kg-embedding>knowledge-graph": "operates-on",
  "llm-extraction>triple": "operates-on",
  "hallucination>llm-extraction": "refines",
  "identifier>entity": "operates-on",
  "sameas>identifier": "operates-on",
  "sameas>entity": "defined-via",
  "entity-resolution>entity": "operates-on",
  "entity-resolution>sameas": "defined-via",
  "entity-resolution>similarity": "assumes",
  "neurosymbolic>llm-extraction": "part-of",
  "neurosymbolic>ontology": "part-of",
  "neurosymbolic>reasoner": "part-of",
  "ontology-grounded-extraction>llm-extraction": "refines",
  "ontology-grounded-extraction>ontology": "assumes",
  "shacl-validation>validation": "is-a",
  "shacl-validation>llm-extraction": "operates-on",
  "propose-verify>llm-extraction": "part-of",
  "propose-verify>reasoner": "part-of",
  "propose-verify>shacl-validation": "part-of",
  "propose-verify>neurosymbolic": "refines",
  "provenance>triple": "operates-on",
  "ner>entity": "operates-on",
  "ner>llm-extraction": "part-of",
  "entity-linking>ner": "operates-on",
  "entity-linking>entity-resolution": "is-a",
  "relation-extraction>ner": "operates-on",
  "relation-extraction>relation": "operates-on",
  "coreference>ner": "operates-on",
  "knowledge-fusion>entity-resolution": "operates-on",
  "knowledge-fusion>provenance": "assumes",
  "conflict-resolution>knowledge-fusion": "part-of",
  "kg-rag>query": "operates-on",
  "kg-rag>hallucination": "operates-on",
  "kg-rag>llm-extraction": "operates-on",
  "text-to-sparql>sparql": "operates-on",
  "text-to-sparql>llm-extraction": "operates-on",
  "schema-induction>ontology": "operates-on",
  "schema-induction>llm-extraction": "operates-on",
  "agent-memory-graph>knowledge-graph": "is-a",
  "agent-memory-graph>llm-extraction": "operates-on",
  "scoring-function>kg-embedding": "part-of",
  "transe>kg-embedding": "is-a",
  "transe>scoring-function": "defined-via",
  "negative-sampling>scoring-function": "operates-on",
  "link-prediction>kg-embedding": "operates-on",
  "link-prediction>scoring-function": "operates-on",
  "triple-classification>scoring-function": "operates-on",
  "triple-classification>link-prediction": "refines",
};

export function prereqKindOf(concept: string, prereq: string): PrereqKind | undefined {
  return PREREQ_KIND[`${concept}>${prereq}`];
}

/** Direct prerequisite ids of a concept. */
export function conceptPrereqs(id: string): string[] {
  return CONCEPT_BY_ID[id]?.prerequisites ?? [];
}

/** All transitive prerequisites of a concept. */
export function conceptAncestors(id: string): Set<string> {
  const seen = new Set<string>();
  const stack = [...conceptPrereqs(id)];
  while (stack.length) {
    const n = stack.pop()!;
    if (seen.has(n)) continue;
    seen.add(n);
    stack.push(...conceptPrereqs(n));
  }
  return seen;
}

/** Concepts a given stage formally introduces. */
export function conceptsForStage(lessonId: string): Concept[] {
  return CONCEPTS.filter((c) => c.introducedIn === lessonId);
}

/** Out-of-page prerequisite concepts for a stage (ADR-0007). */
export function prerequisiteConceptsForStage(lessonId: string): Concept[] {
  const own = new Set(conceptsForStage(lessonId).map((c) => c.id));
  const prereqIds = new Set<string>();
  for (const c of conceptsForStage(lessonId))
    for (const p of c.prerequisites) if (!own.has(p)) prereqIds.add(p);
  return conceptTopoOrder()
    .filter((id) => prereqIds.has(id))
    .map((id) => CONCEPT_BY_ID[id])
    .filter(Boolean);
}

/** Concept ids in a dependency-respecting (simplest-first) order. */
export function conceptTopoOrder(): string[] {
  const visited = new Set<string>();
  const order: string[] = [];
  const visit = (id: string) => {
    if (visited.has(id)) return;
    visited.add(id);
    for (const p of CONCEPT_BY_ID[id]?.prerequisites ?? []) visit(p);
    order.push(id);
  };
  for (const c of CONCEPTS) visit(c.id);
  return order;
}
